export const ErrorCodes = {
  // Add specific error codes for your application here
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  INVALID_IDENTIFIER: "INVALID_IDENTIFIER",
  QUESTION_NOT_FOUND: "QUESTION_NOT_FOUND",
  QUESTION_VALIDATION_ERROR: "QUESTION_VALIDATION_ERROR",
  QUESTION_EMPTY_OPTION: "QUESTION_EMPTY_OPTION",
  QUESTION_NOT_ENOUGH_OPTIONS: "QUESTION_NOT_ENOUGH_OPTIONS",
  QUESTION_NOT_ANSWERABLE: "QUESTION_NOT_ANSWERABLE",
  QUIZ_ERROR: "QUIZ_ERROR",
  QUIZ_NOT_FOUND: "QUIZ_NOT_FOUND",
  QUIZ_VALIDATION_ERROR: "QUIZ_VALIDATION_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
